fix(onesync): prevent ped spawn in vehicles
overextended/es_extended pull request #40
Opened 2022-01-21 06:07 UTC by dolutattoo

Sometimes, CreateAutomobile is creating ped inside created vehicles. It only happens when spawning a model which is also spawned by clients in the same area as POPTYPE_RANDOM_PERMANENT (even if this native only create POPTYPE_PERMANENT entities).

2022-01-22 00:43 UTC, VIRUXE commented
Why would you do something like this? That's a personal choice.

2022-01-23 00:01 UTC, thelindat requested changes

2022-01-23 00:01 UTC, thelindat commented on server/onesync.lua
> +			if ped == 0 then return end
Just check if ped > 0 or ~= 0 to perform the loop, rather than having the return.

2022-01-23 00:01 UTC, thelindat commented on server/onesync.lua
> +			for i=-1, 6 do
We can get the number of seats in a vehicle with GetVehicleModelNumberOfSeats

2022-01-23 05:07 UTC, dolutattoo commented on server/onesync.lua
> +		CreateThread(function()
fixed in next commit

2022-01-23 05:08 UTC, dolutattoo commented on server/onesync.lua
> +			if ped == 0 then return end
done in next commit

2022-01-23 05:08 UTC, dolutattoo commented on server/onesync.lua
> +			for i=-1, 6 do
Yes but only client side, right?

2022-01-23 05:12 UTC, dolutattoo commented
> Why would you do something like this? That's a personal choice.

We're not overriding the native, you can still use `CreateAutomobile` if you want random ped generation inside your vehicles.
`ESX.OneSync.SpawnVehicle` is the serverside function of `ESX.Game.SpawnVehicle` so it shouldn't spawn anything inside the it.

2022-01-27 02:54 UTC, merged